version: "3.7"
services:
  next:
    build:
      args:
        - NODE_VER=22.12.0
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/next-app/node_modules
    networks:
      - line-liff
volumes:
  node_modules:

networks:
  line-liff:
    external: true
